
version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped

  text_to_speech:
    build:
      context: ./services
      dockerfile: Dockerfile.tts
    container_name: tts_service
    ports:
      - "5001:5001"
    restart: unless-stopped

  script_to_srt:
    build:
      context: ./services
      dockerfile: Dockerfile.srt
    container_name: srt_service
    ports:
      - "8000:8000"     ***user ur own port***
    restart: unless-stopped
